# site name
prefixName: 小白白的
siteName: 神秘圣地
# favicon and site master avatar
favicon: /img/favicon.ico
avatar: /img/avatar.jpg
url: http://www.xiaobaibai.com.cn
description: 在神秘圣地可以训练牧师和女巫。
cdn: https://xiaobaibaiyihao.oss-cn-beijing.aliyuncs.com/xiaobaibai
pjax: 1
# 1开启
mathjax: 0

notice: 小白白的个人博客刚刚开通啦，撒花❀*★,°*:.☆(￣▽￣)/$:*.°★* ❀
lazyloadImg: https://xiaobaibaiyihao.oss-cn-beijing.aliyuncs.com/xiaobaibai/img/loader/orange.progress-bar-stripe-loader.svg

menus:
  首页: { path: /, fa: fa-fort-awesome faa-shake }
  归档: { path: /archives, fa: fa-archive faa-shake, submenus: { 
    技术: {path: /categories/技术/, fa: fa-code }, 
    生活: {path: /categories/生活/, fa: fa-file-text-o }, 
    资源: {path: /categories/资源/, fa: fa-cloud-download }, 
    随想: {path: /categories/随想/, fa: fa-commenting-o },
    转载: {path: /categories/转载/, fa: fa-book }
  } }
  清单: { path: javascript:;, fa: fa-list-ul faa-vertical, submenus: { 
    书单: {path: /tags/悦读/, fa: fa-th-list faa-bounce }, 
    番组: {path: /bangumi/, fa: fa-film faa-vertical }, 
    歌单: {path: /music/, fa: fa-headphones },
    图集: {path: /tags/图集/, fa: fa-photo }
  } }
  留言板: { path: /comment/, fa: fa-pencil-square-o faa-tada }
  友人帐: { path: /links/, fa: fa-link faa-shake }
  赞赏: { path: /donate/, fa: fa-heart faa-pulse }
  关于: { path: /, fa: fa-leaf faa-wrench , submenus: { 
    我？: {path: /about/, fa: fa-meetup}, 
    主题: {path: /theme-sakura/, fa: iconfont icon-sakura },
    Lab: {path: /lab/, fa: fa-cogs },
  } }
  客户端: { path: /client/, fa: fa-android faa-vertical }
  RSS: { path: /atom.xml, fa: fa-rss faa-pulse }


# Home page sort type: -1: newer first，1: older first.
homePageSortType: -1
# Home page article shown number)
homeArticleShown: 10
# 背景图片 更好的修改
bg:
  - https://xiaobaibaiyihao.oss-cn-beijing.aliyuncs.com/xiaobaibai/img/cover/banner1.webp
  - https://xiaobaibaiyihao.oss-cn-beijing.aliyuncs.com/xiaobaibai/img/cover/banner2.webp
  - https://xiaobaibaiyihao.oss-cn-beijing.aliyuncs.com/xiaobaibai/img/cover/banner3.webp
  - https://xiaobaibaiyihao.oss-cn-beijing.aliyuncs.com/xiaobaibai/img/cover/banner4.webp
  - https://xiaobaibaiyihao.oss-cn-beijing.aliyuncs.com/xiaobaibai/img/cover/banner5.webp
  - https://xiaobaibaiyihao.oss-cn-beijing.aliyuncs.com/xiaobaibai/img/cover/banner6.webp
# 背景图片样式 空 原图效果 filter-dim 阴影 filter-grid 横条 filter-dot 点点
bgclass: filter-dot

# startdash url, title, desc img
startdash: 
  - {url: /theme-sakura/, title: Sakura, desc: 本站 hexo 主题, img: /img/startdash/sakura.md.png}
  - {url: http://space.bilibili.com/12680013, title: Bilibili, desc: 博主的b站视频, img: /img/startdash/BV1d4411a7xS.png}
  - {url: /, title: xiaobaibai的万事屋, desc: QQ空间, img: /img/startdash/QQzone.png}



# your site build time or founded date
siteBuildingTime: 04/15/2020

#social  url, img PC端配置
social:
  github: {url: http://github.com/jjthe, img: /img/social/github.png}
  sina: {url: https://weibo.com/5966371986?is_all=1, img: /img/social/sina.png}
  wangyiyun: {url: https://music.163.com/#/user/home?id=313024826, img: /img/social/wangyiyun.png}
  zhihu: {url: https://www.zhihu.com/people/xiao-bai-bai-yi-hao, img: /img/social/zhihu.png}
  QQzone: {url: https://user.qzone.qq.com/1432911352/main, img: /img/social/QQ空间.png}
  wechat: {url: /#, qrcode: /img/custom/wechatQRcode.jpg, img: /img/social/wechat.png}
  wechat2: {url: /#, qrcode: /img/custom/QQQRcode.jpg, img: /img/social/QQ.png}

#social  url, img 移动端配置
msocial:
  github: {url: http://github.com/jjthe, fa: fa-github, color: 333}
  weibo: {url: https://weibo.com/5966371986?is_all=1, fa: fa-weibo, color: dd4b39}
  qq: {url: https://user.qzone.qq.com/1432911352/main, fa: fa-qq, color: 25c6fe}

donate:
  paypal: https://www.paypal.me/hojuncn
  alipay: /img/custom/donate/AliPayQR.jpg
  wechat: /img/custom/donate/WeChanQR.jpg
  wechatSQ: /img/custom/donate/WeChanSQ.jpg

# 视频地址为https://cdn.jsdelivr.net/gh/honjun/hojun@1.2/Unbroken.mp4，配置如下
movies:
  url: https://cdn.jsdelivr.net/gh/honjun/hojun@1.2
  # 多个视频用逗号隔开，随机获取。支持的格式目前已知MP4,Flv。其他的可以试下，不保证有用
  name: Unbroken.mp4

aplayer: 
  id: 2660651585
  server: netease
  type: playlist
  fixed: true
  autoplay: false
  loop: all
  order: random
  preload: auto
  volume: 0.7
  mutex: true

# Valine
valine: true
v_appId: GyC3NzMvd0hT9Yyd2hYIC0MN-gzGzoHsz
v_appKey: mgOpfzbkHYqU92CV4IDlAUHQ

